output_dir: t_index/models/ensemble/qwen3-0.6b_alt-tgemma
per_device_train_batch_size: 8
per_device_eval_batch_size: 4
gradient_accumulation_steps: 8
eval_accumulation_steps: 4
metric_for_best_model: loss
eval_steps: 5
weight_decay: 0.01
learning_rate: 1.0e-6
eval_strategy: steps
save_strategy: best
num_train_epochs: 10
lr_scheduler_type: cosine
prediction_loss_only: false
warmup_steps: 0.1
logging_steps: 5
save_total_limit: 2
report_to: wandb
seed: 42
per_model_loss: true
adam_beta2: 0.99
separate_forwards: true
loss_type: llr_pair_sigmoid
optim: stable_adamw
beta1: 1
beta2: 1