output_dir: models/
per_device_train_batch_size: 8
per_device_eval_batch_size: 4
gradient_accumulation_steps: 8
eval_accumulation_steps: 4
metric_for_best_model: spBLEU
eval_steps: 5
weight_decay: 0.01
learning_rate: 1.0e-6
eval_strategy: steps
save_strategy: best
num_train_epochs: 10
lr_scheduler_type: cosine
warmup_steps: 0.1
logging_steps: 5
save_total_limit: 2
report_to: wandb
seed: 42
