output_dir: models/
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
gradient_accumulation_steps: 4
eval_accumulation_steps: 4
metric_for_best_model: spBLEU
greater_is_better: true
eval_steps: 5
weight_decay: 0.01
learning_rate: 2.0e-4
eval_strategy: steps
save_strategy: best
num_train_epochs: 5
lr_scheduler_type: cosine
completion_only_loss: true
warmup_steps: 0.1
logging_steps: 5
save_total_limit: 2
report_to: wandb
seed: 42
