_wandb:
    value:
        cli_version: 0.25.1
        e:
            w8jsmm1dwqrrjcej44904u4lez28anu4:
                args:
                    - --model
                    - aisingapore/Apertus-SEA-LION-v4-8B-IT
                    - --dataset_name_or_path
                    - /data/dania/sea-mt/data/parallel_asian_treebank
                    - --bf16
                    - --per_device_train_batch_size=8
                    - --gradient_accumulation_steps=16
                    - --per_device_eval_batch_size=8
                    - --eval_accumulation_step=16
                    - --eval_steps=5
                    - --evaluation_strategy=steps
                    - --num_train_epochs=10
                    - --weight_decay=0.1
                    - --learning_rate=2e-5
                    - --lr_scheduler=cosine
                    - --max_seq_length=2048
                    - --logging_steps=5
                    - --save_steps=5
                    - --report_to=wandb
                    - --lora_r=64
                    - --lora_alpha=256
                    - --lora_dropout=0.0
                    - --lora_target_modules
                    - q_proj
                    - k_proj
                    - v_proj
                    - o_proj
                    - --lora_bias=none
                codePath: src/train/sft.py
                codePathLocal: src/train/sft.py
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1887976378368"
                        used: "580810784768"
                email: dania.moriazi01@gmail.com
                executable: /home/dania/sea-mt/.venv/bin/python3
                git:
                    commit: 3df808d070623f4fa9e4eb75ce2f33dddb8cd251
                    remote: git@github.com:daniazie/sea-mt-translationese.git
                gpu: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-95886a88-ce04-1816-243c-f275508a7aea
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
                      uuid: GPU-ae7fcc8e-afbf-cf48-a954-0435ae906b49
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Server Edition
                      uuid: GPU-3dde81b2-b7c4-6245-499a-6c125596f013
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Server Edition
                      uuid: GPU-067bf8ba-6d2a-d049-65f1-7de5582a1d25
                host: Hamster
                memory:
                    total: "540582576128"
                os: Linux-5.15.0-153-generic-x86_64-with-glibc2.35
                program: /home/dania/sea-mt/src/train/sft.py
                python: CPython 3.12.13
                root: /home/dania/sea-mt
                startedAt: "2026-03-27T03:05:53.235427Z"
                writerId: w8jsmm1dwqrrjcej44904u4lez28anu4
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 98
                - 100
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 98
                - 100
            "3":
                - 13
                - 16
            "4": 3.12.13
            "5": 0.25.1
            "6": 4.57.6
            "12": 0.25.1
            "13": linux-x86_64
completion_only_loss:
    value: false
epochs:
    value: 10
lora:
    value:
        alpha: 256
        bias: none
        dropout: 0
        r: 64
lr:
    value: 2e-05
weight_decay:
    value: 0.1
