data_path: /data/dania/sea-mt/data/t-index_data/synthetic/enms/*/test.jsonl
validation_path: /data/dania/sea-mt/data/t-index_data/synthetic/enms/parallel_asian_treebank_qwen/valid.jsonl
prompt_field: source
completion_positive_field: foreignization
completion_negative_field: domestication
prompt_template_positive: "Translate the following text into Malay.\n\n{input}"
prompt_template_negative: "Translate the following text into Malay.\n\n{input}"
batch_size: 4
num_proc: 10
max_length: 1024
model_args:
  torch_dtype: bfloat16
device: cuda